# This file overrides https://github.com/bbatsov/rubocop/blob/master/config/default.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'config/initializers/kaminari_config.rb'
  DisplayCopNames: true
#Rails:
#  Enabled: true

#Rails/Output:
#  Exclude:
#    - 'config/unicorn/**/*'
#    -
Layout/MultilineBlockLayout:
  Exclude:
    - 'spec/**/*_spec.rb'

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  CountComments: false
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 30

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 30

Naming/AccessorMethodName:
  Exclude:
    - 'app/controllers/**/*'

Style/AsciiComments:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false
#Rails/OutputSafety:
#  Enabled: true
#  Exclude:
#    - 'app/helpers/**/*.rb'

#Rails/InverseOf:
#  Enabled: false