default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "root") %>
  host: <%= ENV.fetch("MYSQL_HOST", "database") %>
development:
  <<: *default
  database: nampa_checker_development
test:
  <<: *default
  database: nampa_checker_test
production:
  <<: *default
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  database: nampa_checker_production
  username: nampa_checker
  password: <%= ENV['NAMPA_CHECKER_DATABASE_PASSWORD'] %>
